


cluster:
  mkdir -p output/logs/ &&
  sbatch
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --time=2:00:00
    --output=output/logs/%j.out
    --partition brief-low
default-resources:
  - mem_mb=26000
jobs: 40
keep-going: True
rerun-incomplete: True
printshellcmds: True

groups:
  - blastp=groupjob
  - blast_sort=groupjob
  - get_seq=groupjob
  - merge_seq=groupjob
  - msa=groupjob
  - process=groupjob  
  - process=groupjob
  - weblogo=groupjob
  - ncbi_format=groupjob
group-components:
  - groupjob=14

cores: 70
max-jobs-per-second: 25
